### ISSUE TITLE
Documentation is inadequate

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [openshift/deadmanssnitch-operator#58]
I am trying to deploy `deadmanssnitch-operator` on an Openshift OCP v4.4 cluster. I can't find anything related to it's configuration or usage in the given documentation. And this is acting as a hindrance in trying to set it up, i have deployed the operator but the pod is stuck in a `CrashLoopBackOff`. 
Even a brief documentation regarding setting it up would be of immense help for anyone that is trying to use this operator.

**Comment by jewzaam** [comment]
Configuration is put in a secret.
The name of the secret: https://github.com/openshift/deadmanssnitch-operator/blob/master/pkg/controller/deadmanssnitch/deadmanssnitch_controller.go#L34
The secret data key for the DMS API Key: https://github.com/openshift/deadmanssnitch-operator/blob/master/pkg/controller/deadmanssnitch/deadmanssnitch_controller.go#L36
The secret data key for the DMS Tag (applied to the DMS service): https://github.com/openshift/deadmanssnitch-operator/blob/master/pkg/controller/deadmanssnitch/deadmanssnitch_controller.go#L38

Please review the controller for the operator to understand how it works fully, sorry we don't have sufficient docs for setup and use.  Baring that, which if you'd like to contribute to the readme it would be great, it's all in the code and this is a pretty simple operator.   Not trying to say "the code is the documentation" but "baring documentation, please look at the code". 

Hope this helps.

**Comment by ahmedwaleedmalik** [comment]
I was able to figure this out.
This PR should fix this issue: #60

**Comment by jewzaam** [comment]
Thanks, the PR should merge automatically once tests pass.

**Comment by jewzaam** [comment]
Resolved in https://github.com/openshift/deadmanssnitch-operator/pull/60
